# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          GWAN NAMGOONG
baseurl:        ""
url:            "http://1987wish.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         GWAN NAMGOONG
  url:          http://1987wish.com
  email:        0817wish@gmail.com  
  github:       1987wish
#  twitter:      playpingpong

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/1987wish/1987wish.github.io